# Generated by Django 4.1.3 on 2023-02-07 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_products',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
