# Generated by Django 4.1.7 on 2023-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerceApp", "0002_featured_products_date_posted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_starts", models.DateTimeField()),
                ("date_ends", models.DateTimeField()),
                ("offer", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="featured_products",
            name="image",
            field=models.ImageField(upload_to="static/Featured_Products_images"),
        ),
    ]
